#!/bin/bash

iptables-legacy -P OUTPUT DROP
iptables-legacy -P INPUT DROP
iptables-legacy -P FORWARD DROP
ip6tables-legacy -P OUTPUT DROP 2>/dev/null
ip6tables-legacy -P INPUT DROP 2>/dev/null
ip6tables-legacy -P FORWARD DROP 2>/dev/null

echo "[$(date -Iseconds)] Firewall is up, everything has to go through the vpn"